#!/bin/sh
#
# Pre-commit script to prevent commit if the make fails

# Redirect output to stderr.
exec 1>&2

if cd 'L8' && make

then
	echo "Make successful"
else
	cat <<\EOF
Error: could not make pdf

EOF
	exec git add paper.log paper.pdf plot-data.png
	exit 1
fi
